# Generated by Django 2.0.9 on 2018-12-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('turmas', models.CharField(max_length=1000)),
                ('disciplinas', models.CharField(max_length=1000)),
            ],
        ),
    ]
